# @package _group_
encoder_blocks: 2
adv_blocks: 2
decoder_blocks: 2
latent_dims: 6
latent_multiplier: 15
lr: 1e-3
adv_weight: 1.0
target_weight: 1.0
reg_weight: 1.0
s_as_input: true
mmd_kernel: "linear"
scheduler_rate: 0.99
weight_decay: 1e-6
use_iw: false
