# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass
from omegaconf import MISSING
from typing import Optional
from typing import Tuple


@dataclass
class LilliputDataModuleConf:
    _target_: str = "paf.data_modules.lilliput_datamodule.LilliputDataModule"
    alpha: float = MISSING
    gamma: float = MISSING
    seed: int = MISSING
    num_samples: int = MISSING
    num_workers: int = MISSING
    batch_size: int = MISSING
    cf_available: bool = True
    train_dims: Optional[Tuple[int, ...]] = None
