repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variable
          - --ignore-init-module-imports
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args:
        - --py36-plus
        - --keep-runtime-typing
#  - repo: https://github.com/pycqa/pydocstyle
#    rev: 5.1.1  # pick a git hash / tag to point to
#    hooks:
#      - id: pydocstyle
#        args:
#          - --convention=google
#          - --add-ignore=D105,D107
#          - --ignore-decorators=implements|overload|property
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: name-tests-test
      - id: debug-statements
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [ python ]
#        args:
#          [
#              "-rn",
#              "-sn",
#              "--rcfile=.pylintrc",
#          ]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#      - id: mypy
#        name: mypy
#        entry: mypy
#        language: python
#        types: [ python ]

