[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
optuna = "^2.1.0"
teext = "^0.1.2"
wandb = "^0.10.5"
plotly = "^4.11.0"
ethicml = {git = "https://github.com/predictive-analytics-lab/EthicML.git"}
pytorch-lightning = "^1.0.6"
hydra-core = "^1.0.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
data-science-types = "^0.2.18"
mypy = "^0.782"
pydocstyle = "^5.1.1"
pylint = "^2.6.0"
pytest = "^6.1.0"
pytest-cov = "^2.10.1"
pre-commit = "^2.7.1"

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run = "src.main:encoder"

[tool.black]
line-length = 100
target-version = ['py37']
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
