# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass
from omegaconf import MISSING
from typing import Optional
from typing import Tuple


@dataclass
class LilliputDataModuleConf:
    _target_: str = "paf.data_modules.LilliputDataModule"
    alpha: float = MISSING
    gamma: float = MISSING
    seed: int = MISSING
    num_samples: int = MISSING
    num_workers: int = MISSING
    batch_size: int = MISSING
    cf_available: bool = True
    train_dims: Optional[Tuple[int, ...]] = None


@dataclass
class ThirdWayDataModuleConf:
    _target_: str = "paf.data_modules.ThirdWayDataModule"
    acceptance_rate: float = MISSING
    alpha: float = MISSING
    beta: float = MISSING
    gamma: float = MISSING
    seed: int = MISSING
    num_samples: int = MISSING
    num_workers: int = MISSING
    batch_size: int = MISSING
    num_features: int = MISSING
    xi: float = MISSING
    num_hidden_features: int = MISSING
    cf_available: bool = True
    train_dims: Optional[Tuple[int, ...]] = None


@dataclass
class SimpleXDataModuleConf:
    _target_: str = "paf.data_modules.SimpleXDataModule"
    alpha: float = MISSING
    gamma: float = MISSING
    seed: int = MISSING
    num_samples: int = MISSING
    num_workers: int = MISSING
    batch_size: int = MISSING
    cf_available: bool = True
    train_dims: Optional[Tuple[int, ...]] = None


@dataclass
class SimpleAdultDataModuleConf:
    _target_: str = "paf.data_modules.SimpleAdultDataModule"
    batch_size: int = MISSING
    bin_nat: bool = MISSING
    bin_race: bool = MISSING
    seed: int = MISSING
    num_workers: int = MISSING
    sens: str = MISSING
    cf_available: bool = False
