# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING


@dataclass
class CycleGanConf:
    _target_: str = "paf.architectures.model.CycleGan"
    blocks: int = MISSING
    adv_blocks: int = MISSING
    latent_multiplier: int = MISSING
    batch_size: int = MISSING
    g_weight_decay: float = MISSING
    d_weight_decay: float = MISSING
    scheduler_rate: float = 0.99
    d_lr: float = 0.0002
    g_lr: float = 0.0002
    debug: bool = False


@dataclass
class NearestNeighbourConf:
    _target_: str = "paf.architectures.model.NearestNeighbour"
