# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass


@dataclass
class CycleGanConf:
    _target_: str = "paf.architectures.model.CycleGan"
    d_lr: float = 0.0002
    g_lr: float = 0.0002
    epoch_decay: int = 200


@dataclass
class NearestNeighbourConf:
    _target_: str = "paf.architectures.model.NearestNeighbour"
