# this is the main config file
defaults:
  - hydra/launcher: basic  # use ray launcher to run things in parallel

  # default config files
  - data/schema: synth
  - data: synthetic_1 # `configs/data/synthetic_1.yaml`
  - enc: basic  # `configs/model/basic.yaml`
  - clf: basic  # `configs/model/basic.yaml`
  - training: simple # `configs/training/simple.yaml`
