#
# usage: hydra/launcher=slurm_turing
#
defaults:
  - submitit_slurm
  - _self_

partition: turing
cpus_per_task: 10  # on turing, we have 10 CPUs per GPU
timeout_min: 99999  # 99999 minutes = a few months
mem_gb: 18
