# this is the main config file
defaults:
  - config_schema
  - data: synth # `configs/data/synthetic_1.yaml`
  - enc: basic  # `configs/model/basic.yaml`
  - clf: basic  # `configs/model/basic.yaml`
  - exp: srv
  - trainer: srv # `configs/training/simple.yaml`
