defaults:
  - /schema/enc: enc_schema
encoder_blocks: 0
adv_blocks: 0
decoder_blocks: 0
latent_dims: 5
latent_multiplier: 1
lr: 1e-3
adv_weight: 1.0
target_weight: 1.0
reg_weight: 1e-3
s_as_input: true
mmd_kernel: "linear"
scheduler_rate: 0.999
weight_decay: 1e-6
use_iw: false
