defaults:
  - /schema/enc: enc_schema
  - _self_

encoder_blocks: 2
adv_blocks: 2
decoder_blocks: 2
latent_dims: 6
latent_multiplier: 15
lr: 1e-3
adv_weight: 1.0
mmd_weight: 1.0
target_weight: 1.0
cycle_weight: 0.0
proxy_weight: 1.0
s_as_input: true
mmd_kernel: "LINEAR"
scheduler_rate: 0.99
weight_decay: 1e-6
debug: false
