defaults:
  - /schema/clf: clf_schema
  - _self_

encoder_blocks: 3
adv_blocks: 1
decoder_blocks: 1
latent_dims: 10
latent_multiplier: 10
lr: 3e-4
adv_weight: 0.0
pred_weight: 1.0
s_as_input: true
mmd_kernel: "RBF"
scheduler_rate: 0.99
weight_decay: 1e-6
use_iw: false
debug: false
