defaults:
  - /clf_schema
encoder_blocks: 3
adv_blocks: 3
decoder_blocks: 3
latent_dims: 1
latent_multiplier: 1
lr: 1e-3
adv_weight: 1.0
recon_weight: 1.0
reg_weight: 1e-3
s_as_input: true
mmd_kernel: "RBF"
scheduler_rate: 0.99
use_iw: false
