defaults:
  - /schema/clf: clf_schema
  - _self_

encoder_blocks: 5
adv_blocks: 2
decoder_blocks: 5
latent_dims: 2
latent_multiplier: 25
lr: 1e-4
adv_weight: 1.0
pred_weight: 1.0
mmd_weight: 1.0
s_as_input: true
mmd_kernel: "RBF"
scheduler_rate: 0.99
weight_decay: 1e-6
use_iw: false
debug: false
batch_size: ${data.train_batch_size}
