defaults:
  - /schema/clf: clf_schema
  - _self_

encoder_blocks: 5
adv_blocks: 2
decoder_blocks: 2
latent_dims: 3
latent_multiplier: 25
lr: 3e-4
adv_weight: 1.0
pred_weight: 4.0
mmd_weight: 1.0
s_as_input: true
mmd_kernel: "RBF"
scheduler_rate: 0.99
weight_decay: 1e-6
use_iw: true
debug: false
