defaults:
  - /schema/clf: clf_schema
  - _self_

encoder_blocks: 1
adv_blocks: 1
decoder_blocks: 1
latent_dims: 1
latent_multiplier: 1
lr: 1e-2
adv_weight: 0.5
pred_weight: 1.0
mmd_weight: 0.5
s_as_input: true
mmd_kernel: "LINEAR"
scheduler_rate: 0.99
weight_decay: 1e-6
use_iw: false
debug: false
