defaults:
  - /schema/clf: clf_schema
encoder_blocks: 2
adv_blocks: 2
decoder_blocks: 2
latent_dims: 1
latent_multiplier: 10
lr: 1e-3
adv_weight: 0.0
target_weight: 1.0
reg_weight: 1e-3
s_as_input: true
mmd_kernel: "LINEAR"
scheduler_rate: 0.99
weight_decay: 1e-4
use_iw: true
