defaults:
  - /schema/clf: clf_schema
  - _self_

encoder_blocks: 2
adv_blocks: 2
decoder_blocks: 2
latent_dims: 3
latent_multiplier: 10
lr: 3e-4
adv_weight: 0.5
pred_weight: 1.0
mmd_weight: 0.5
s_as_input: true
mmd_kernel: "RBF"
scheduler_rate: 0.99
weight_decay: 1e-4
use_iw: true
debug: false
